import networkx as nx

class Node:

  def __init__(self, name, neighbors):
    self.name = name
    self.neighbors = neighbors

def add_black_cities(board):
  ''' Add the black cities as nodes to the board. '''
  board.add_node('Algiers')
  board.add_node('Cairo')
  board.add_node('Istanbul')
  board.add_node('Baghdad')
  board.add_node('Moscow')
  board.add_node('Riyadh')
  board.add_node('Tehran')
  board.add_node('Karachi')
  board.add_node('Mumbai')
  board.add_node('Delhi')
  board.add_node('Chennai')
  board.add_node('Kolkata')

def add_blue_cities(board):
  ''' Add the blue cities as nodes to the board. '''
  board.add_node('San Francisco')
  board.add_node('Chicago')
  board.add_node('Atlanta')
  board.add_node('Montreal')
  board.add_node('Washington')
  board.add_node('New York')
  board.add_node('Madrid')
  board.add_node('London')
  board.add_node('Paris')
  board.add_node('Milan')
  board.add_node('St. Petersburg')

def add_red_cities(board):
  ''' Add the red cities as nodes to the board. '''
  board.add_node('Bangkok')
  board.add_node('Jakarta')
  board.add_node('Beijing')
  board.add_node('Shanghai')
  board.add_node('Hong Kong')
  board.add_node('Taipei')
  board.add_node('Ho Chi Minh')
  board.add_node('Manila')
  board.add_node('Sydney')
  board.add_node('Osaka')
  board.add_node('Tokyo')

def add_yellow_cities(board):
  ''' Add the yellow cities as nodes to the board. '''
  board.add_node('Los Angeles')
  board.add_node('Mexico City')
  board.add_node('Lima')
  board.add_node('Miami')
  board.add_node('Santiago')
  board.add_node('Bogota')
  board.add_node('Buenos Aires')
  board.add_node('Sao Paulo')
  board.add_node('Lagos')
  board.add_node('Kinshasa')
  board.add_node('Johannesburg')
  board.add_node('Khartoum')

def add_edges(board):
  board.add_edge('San Francisco', 'Tokyo')
  board.add_edge('San Francisco', 'Manila')
  board.add_edge('San Francisco', 'Los Angeles')
  board.add_edge('San Francisco', 'Chicago')
  board.add_edge('Los Angeles', 'Sydney')
  board.add_edge('Los Angeles', 'Mexico City')
  board.add_edge('Mexico City', 'Miami')
  board.add_edge('Mexico City', 'Bogota')
  board.add_edge('Mexico City', 'Lima')
  board.add_edge('Mexico City', 'Chicago')
  board.add_edge('Chicago', 'Atlanta')
  board.add_edge('Chicago', 'Montreal')
  board.add_edge('Atlanta', 'Washington')
  board.add_edge('Atlanta', 'Miami')
  board.add_edge('Lima', 'Bogota')
  board.add_edge('Lima', 'Santiago')
  board.add_edge('Bogota', 'Miami')
  board.add_edge('Bogota', 'Sao Paulo')
  board.add_edge('Bogota', 'Buenos Aires')
  board.add_edge('Miami', 'Washington')
  board.add_edge('Montreal', 'Washington')
  board.add_edge('Montreal', 'New York')
  board.add_edge('Washington', 'New York')
  board.add_edge('Buenos Aires', 'Sao Paulo')
  board.add_edge('New York', 'Madrid')
  board.add_edge('New York', 'London')
  board.add_edge('Sao Paulo', 'Madrid')
  board.add_edge('Sao Paulo', 'Lagos')
  board.add_edge('Madrid', 'London')
  board.add_edge('Madrid', 'Paris')
  board.add_edge('Madrid', 'Algiers')
  board.add_edge('London', 'Paris')
  board.add_edge('London', 'Essen')
  board.add_edge('Lagos', 'Kinshasa')
  board.add_edge('Lagos', 'Khartoum')
  board.add_edge('Paris', 'Algiers')
  board.add_edge('Paris', 'Essen')
  board.add_edge('Paris', 'Milan')
  board.add_edge('Algiers', 'Istanbul')
  board.add_edge('Algiers', 'Cairo')
  board.add_edge('Essen', 'Milan')
  board.add_edge('Essen', 'St. Petersburg')
  board.add_edge('Kinshasa', 'Khartoum')
  board.add_edge('Kinshasa', 'Johannesburg')
  board.add_edge('Milan', 'Istanbul')
  board.add_edge('Cairo', 'Istanbul')
  board.add_edge('Cairo', 'Khartoum')
  board.add_edge('Cairo', 'Baghdad')
  board.add_edge('Cairo', 'Riyadh')
  board.add_edge('Johannesburg', 'Khartoum')
  board.add_edge('Istanbul', 'St. Petersburg')
  board.add_edge('Istanbul', 'Baghdad')
  board.add_edge('Istanbul', 'Moscow')
  board.add_edge('St. Petersburg', 'Moscow')
  board.add_edge('Baghdad', 'Riyadh')
  board.add_edge('Baghdad', 'Tehran')
  board.add_edge('Baghdad', 'Karachi')
  board.add_edge('Riyadh', 'Karachi')
  board.add_edge('Tehran', 'Karachi')
  board.add_edge('Tehran', 'Delhi')
  board.add_edge('Karachi', 'Mumbai')
  board.add_edge('Karachi', 'Delhi')
  board.add_edge('Mumbai', 'Delhi')
  board.add_edge('Mumbai', 'Chennai')
  board.add_edge('Chennai', 'Kolkata')
  board.add_edge('Chennai', 'Bangkok')
  board.add_edge('Chennai', 'Jakarta')
  board.add_edge('Kolkata', 'Bangkok')
  board.add_edge('Kolkata', 'Hong Kong')
  board.add_edge('Bangkok', 'Hong Kong')
  board.add_edge('Bangkok', 'Jakarta')
  board.add_edge('Bangkok', 'Ho Chi Minh')
  board.add_edge('Jakarta', 'Ho Chi Minh')
  board.add_edge('Jakarta', 'Sydney')
  board.add_edge('Beijing', 'Shanghai')
  board.add_edge('Beijing', 'Seoul')
  board.add_edge('Shanghai', 'Hong Kong')
  board.add_edge('Shanghai', 'Seoul')
  board.add_edge('Shanghai', 'Taipei')
  board.add_edge('Shanghai', 'Tokyo')
  board.add_edge('Hong Kong', 'Ho Chi Minh')
  board.add_edge('Hong Kong', 'Taipei')
  board.add_edge('Hong Kong', 'Manila')
  board.add_edge('Ho Chi Minh', 'Manila')
  board.add_edge('Seoul', 'Tokyo')
  board.add_edge('Taipei', 'Manila')
  board.add_edge('Taipei', 'Osaka')
  board.add_edge('Tokyo', 'Osaka')

def make_board():
  board = nx.Graph()
  add_black_cities(board)
  add_blue_cities(board)
  add_red_cities(board)
  add_yellow_cities(board)
  add_edges(board)
  return board

if __name__ == '__main__':
  #board = make_board()
  #nx.write_edgelist(board, 'board.dat', delimiter=',')
  board = nx.read_edgelist('board.dat', delimiter=',')
  for node in board:
    print board.neighbors(node)


